Project=OrangeHRM Selenium Python Automation Framework
Team=PyAutomation Crew
Framework=Behave + Selenium + Python
Browser=Chrome
Environment=QA
OS=Windows 11
Execution=Local Execution
URL=https://opensource-demo.orangehrmlive.com/
Report=Allure Report